import Head from 'next/head'
import Navbar from '../components/navbar/index'
import Header from '../components/header/header'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Undsgn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <main>
        <Navbar/>
        <Header/>
      </main>

      <footer>

      </footer>
    </div>
  )
}
